import Link from "next/link";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { DemoHeader } from "@/components/demo/demo-header";
import { DirectionalStudyEvidence } from "@/components/demo/directional-study-evidence";
import { getBuildVersion } from "@/server/build-week/version";

const proofMoments = [
  { title: "Incorrect work-mode interpretation", observed: "A practical work-mode mismatch could read like a technical capability failure.", reproduced: "Frozen cases showed identical technical evidence receiving a different user interpretation when only work mode changed.", repaired: "Technical Fit Score and practical compatibility were separated in data, UI, and explanation.", regression: "Work-mode mutation cases prove unchanged technical points, score, and receipt arithmetic." },
  { title: "Scoring-budget defect", observed: "Preferred weighting could cancel itself and an earlier allocation did not reconcile to the full 100-point budget.", reproduced: "Micro-point ledgers exposed both the cancellation and the missing allocation deterministically.", repaired: "Bounded class transfers restored Preferred contribution while preserving the exact 100,000,000 micro-point total.", regression: "Property cases, full-score fixtures, class caps, transfers, and rounding now reconcile exactly." },
  { title: "Receipt and verifier construction", observed: "A displayed score could not independently prove its source inputs, arithmetic, evidence IDs, or canonical hash.", reproduced: "Tampered receipts demonstrated that valid-looking JSON was not sufficient evidence.", repaired: "JobPilot added frozen inputs, a canonical Score Receipt, and independent web, API, and CLI verification.", regression: "All bundled receipts reproduce; adversarial changes fail closed without external requests." },
  { title: "Missing Tailwind production pipeline", observed: "The development interface looked styled while the production CSS bundle lacked required Tailwind output.", reproduced: "A production build and route capture exposed the missing pipeline rather than a component-level styling bug.", repaired: "The Tailwind/PostCSS production path was restored and its generated bundle bound to a hash.", regression: "Dedicated CSS pipeline tests and production visual checks now guard the compiled result." },
  { title: "Dense Job Detail transformation", observed: "The Job Detail read like an audit report before answering whether the role deserved attention.", reproduced: "Decision-critical facts competed with arithmetic, evidence, and provenance at the same visual level.", repaired: "Fit, priority, strongest match, biggest gap, and next action moved first; proof became progressive disclosure.", regression: "Responsive browser checks preserve both the fast decision view and the complete inspectable evidence path." },
] as const;
const journey = ["DISCOVER", "PRIORITIZE", "UNDERSTAND", "APPLY", "TRACK"];

export default function Page() {
  const version = getBuildVersion();
  return <div className="min-h-screen bg-[#fbf7ed] text-[#173d2d]"><DemoHeader /><main className="mx-auto max-w-6xl px-5 py-12"><p className="eyebrow">OpenAI Build Week · Apps for Your Life</p><h1 className="mt-4 max-w-5xl font-serif text-5xl leading-tight sm:text-6xl">Codex helped turn application fatigue into five reproducible product repairs.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[#587064]">The build story is not “AI generated an interface.” Codex helped observe defects, reproduce them with evidence, repair the product boundary, and preserve each correction in regression tests.</p>
    <p className="mt-4 text-xs font-semibold tracking-[.08em] text-[#587064]">Build {version.productShortCommit} Â· Study Evidence RC</p>
    <ol aria-label="JobPilot product journey" className="mt-9 grid overflow-hidden rounded-2xl border border-[#173d2d]/10 bg-[#e8efe6] sm:grid-cols-5">{journey.map((item, index) => <li key={item} className="flex min-h-20 items-center gap-3 border-b border-[#173d2d]/10 p-4 text-xs font-bold tracking-[.08em] last:border-0 sm:border-b-0 sm:border-r"><span className="text-[#a1742d]">{index + 1}</span>{item}</li>)}</ol>
    <DirectionalStudyEvidence compact />
    <section className="mt-12"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Observed development evidence</p><h2 className="mt-2 font-serif text-4xl">Five proof moments</h2></div><Link href="/demo/trust" className="button-secondary">Inspect Trust Lab</Link></div><div className="mt-6 space-y-5">{proofMoments.map((moment, index) => <article key={moment.title} className="paper-card"><div className="grid gap-5 lg:grid-cols-[64px_1fr]"><span className="grid size-12 place-items-center rounded-full bg-[#173d2d] font-mono text-sm text-[#fffaf0]">{String(index + 1).padStart(2, "0")}</span><div><h3 className="font-serif text-3xl">{moment.title}</h3><dl className="mt-5 grid gap-3 md:grid-cols-2"><ProofStep label="Observed" body={moment.observed} /><ProofStep label="Reproduced" body={moment.reproduced} /><ProofStep label="Repaired" body={moment.repaired} /><ProofStep label="Regression tested" body={moment.regression} /></dl></div></div></article>)}</div></section>
    <section className="mt-10 grid gap-5 md:grid-cols-3"><Proof title="Production reality" body="A read-only, public-safe snapshot proves current aggregate catalog and source coverage without copying private records." /><Proof title="Decision utility" body="Today’s Shortlist turns an endless feed into three explainable next decisions with no hidden aggregate score." /><Proof title="Bounded AI" body="Gemma remains primary, code owns every score, and four gpt-5.6-sol reviews are prepared through Codex, hash-bound, not live, and zero-API." /></section>
    <section className="mt-10 rounded-3xl bg-[#173d2d] p-7 text-[#fffaf0]"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#d7c68d]">Neutral differentiation</p><h2 className="mt-3 font-serif text-3xl">From fragmented searching to one controlled decision loop.</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-[#dce8df]">Traditional job search often separates discovery, comparison, explanation, employer handoff, and tracking. JobPilot connects those steps without claiming complete-market coverage or automating the user’s application decision.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/about/coverage" className="button-primary border-[#fffaf0] bg-[#fffaf0] text-[#173d2d]">Inspect coverage proof</Link><Link href="/demo/shortlist" className="button-secondary border-white/20 bg-white/10 text-white">Open Today&apos;s Shortlist</Link><Link href="/" className="button-secondary border-white/20 bg-white/10 text-white">Return to product <ArrowRight className="size-4" /></Link></div></section>
  </main></div>;
}

function ProofStep({ label, body }: { label: string; body: string }) { return <div className="rounded-2xl bg-[#edf1e8] p-4"><dt className="metric-label">{label}</dt><dd className="mt-2 text-sm leading-6 text-[#587064]">{body}</dd></div>; }
function Proof({ title, body }: { title: string; body: string }) { return <article className="paper-card"><CheckCircle2 className="size-5 text-[#a1742d]" /><h2 className="mt-4 font-serif text-2xl">{title}</h2><p className="mt-3 text-sm leading-7 text-[#587064]">{body}</p></article>; }
