"use client";

import { useState } from "react";
import { Check, SlidersHorizontal } from "lucide-react";
import { DemoHeader } from "@/components/demo/demo-header";
import { usePrivateProfile } from "@/components/profile/profile-store";
import type { WorkPreferences } from "@/lib/private-profile";

export function PreferencesPage() {
  const store = usePrivateProfile();
  const [draft, setDraft] = useState<WorkPreferences>(store.preferences);
  const [saved, setSaved] = useState(false);
  const toggleMode = (mode: "REMOTE" | "HYBRID" | "ONSITE") => setDraft({ ...draft, acceptedWorkModes: draft.acceptedWorkModes.includes(mode) ? draft.acceptedWorkModes.filter((item) => item !== mode) : [...draft.acceptedWorkModes, mode] });
  return <div className="min-h-screen bg-[#fbf7ed] text-[#173d2d]"><DemoHeader /><main className="mx-auto max-w-4xl px-5 py-10"><p className="eyebrow"><SlidersHorizontal className="size-4" /> Practical constraints</p><h1 className="mt-3 font-serif text-5xl">Work preferences</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-[#587064]">These preferences affect Apply Priority and blocker guidance. They never silently change technical Fit Score.</p><section className="paper-card mt-8 space-y-6"><fieldset><legend className="font-serif text-2xl">Accepted work modes</legend><div className="mt-4 flex flex-wrap gap-3">{(["REMOTE", "HYBRID", "ONSITE"] as const).map((mode) => <label key={mode} className="choice-control"><input type="checkbox" checked={draft.acceptedWorkModes.includes(mode)} onChange={() => toggleMode(mode)} /> {mode[0] + mode.slice(1).toLowerCase()}</label>)}</div></fieldset><label className="block font-bold">Preferred locations<textarea className="form-control" rows={3} value={draft.preferredLocations.join("\n")} onChange={(event) => setDraft({ ...draft, preferredLocations: event.target.value.split(/\n/).map((value) => value.trim()).filter(Boolean) })} /></label><label className="block font-bold">Remote eligibility<select className="form-control" value={draft.remoteEligibility} onChange={(event) => setDraft({ ...draft, remoteEligibility: event.target.value as WorkPreferences["remoteEligibility"] })}><option value="YES">Eligible for remote work</option><option value="NO">Not eligible for remote work</option><option value="NEEDS_CLARIFICATION">Needs clarification</option></select></label><label className="block font-bold">Maximum travel percentage<input className="form-control" type="number" min="0" max="100" value={draft.maximumTravelPercent ?? ""} onChange={(event) => setDraft({ ...draft, maximumTravelPercent: event.target.value === "" ? null : Number(event.target.value) })} /></label><label className="choice-control"><input type="checkbox" checked={draft.willingToRelocate} onChange={(event) => setDraft({ ...draft, willingToRelocate: event.target.checked })} /> Open to relocation</label><label className="block font-bold">Optional authorization note<textarea className="form-control" rows={3} maxLength={240} value={draft.authorizationNote} onChange={(event) => setDraft({ ...draft, authorizationNote: event.target.value })} /></label><button type="button" className="button-primary" onClick={() => { store.setPreferences(draft); setSaved(true); }}><Check className="size-4" /> Save Preferences</button>{saved && <p role="status" className="text-sm font-bold text-[#315c49]">Preferences saved locally.</p>}</section></main></div>;
}
