"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, Bookmark, Bot, Clipboard, Download, ExternalLink, ShieldAlert } from "lucide-react";
import { DemoHeader } from "@/components/demo/demo-header";
import { useDemoTracker } from "@/components/demo/demo-store";
import type { DemoCandidate, DemoJob } from "@/lib/demo-contract";
import { CALIBRATION_DISCLOSURE, SCORE_DISCLOSURE } from "@/lib/demo-contract";
import type { ScoreAnalysis } from "@/server/build-week/scorer";
import type { ApplicationStrategy, DemoProviderMode } from "@/server/build-week/strategy";

type StrategyState = "NOT_REQUESTED" | "RUNNING" | "COMPLETE" | "MODEL_UNAVAILABLE" | "RATE_LIMITED" | "FAILED";
type ExperienceRow = { requirementId: string; requestedYears: number; relevantYears: number; intervals: string[]; coefficients: string[]; overlappingMonthsRemoved: number; maximumPoints: number; earnedPoints: number };

function points(value: number) { return (value / 1_000_000).toFixed(2); }

export function JobDetail({ job, candidate, analysis, initialMode, experienceRows }: { job: DemoJob; candidate: DemoCandidate; analysis: ScoreAnalysis; initialMode: DemoProviderMode; experienceRows: ExperienceRow[] }) {
  const tracker = useDemoTracker();
  const saved = Boolean(tracker.records[job.id]);
  const [strategyState, setStrategyState] = useState<StrategyState>("NOT_REQUESTED");
  const [strategy, setStrategy] = useState<ApplicationStrategy | null>(null);
  const [provider, setProvider] = useState<{ mode: DemoProviderMode; model: string; live: boolean } | null>(null);
  const [copied, setCopied] = useState(false);
  const evidence = new Map(candidate.evidence.map((item) => [item.id, item]));
  const requestStrategy = async () => {
    setStrategyState("RUNNING"); setStrategy(null);
    try {
      const response = await fetch("/api/demo/strategy", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ jobId: job.id, mode: initialMode === "BUILD_WEEK_GPT56" ? "live" : "fixture" }) });
      const payload = await response.json();
      if (!response.ok) { setStrategyState(response.status === 429 ? "RATE_LIMITED" : response.status === 503 ? "MODEL_UNAVAILABLE" : "FAILED"); return; }
      setStrategy(payload.strategy); setProvider(payload.provider); setStrategyState("COMPLETE");
    } catch { setStrategyState("FAILED"); }
  };
  const downloadReceipt = () => {
    const url = URL.createObjectURL(new Blob([JSON.stringify(analysis.receipt, null, 2)], { type: "application/json" }));
    const link = document.createElement("a"); link.href = url; link.download = `${job.id}-score-receipt.json`; link.click(); URL.revokeObjectURL(url);
  };
  const copyHash = async () => { await navigator.clipboard.writeText(String(analysis.receipt.receiptHash)); setCopied(true); setTimeout(() => setCopied(false), 1600); };
  const positive = analysis.capabilityGroups.filter((group) => group.earnedMidMicroPoints > 0).sort((a, b) => b.earnedMidMicroPoints - a.earnedMidMicroPoints).slice(0, 3);
  const losses = analysis.capabilityGroups.filter((group) => group.pointsLostMicroPoints > 0).sort((a, b) => b.pointsLostMicroPoints - a.pointsLostMicroPoints).slice(0, 3);
  const uncertain = analysis.capabilityGroups.filter((group) => group.matchClass === "UNKNOWN" || group.matchClass === "PARTIAL" || group.matchClass === "WEAK" || group.matchClass === "STRONG_EQUIVALENT");

  return <div className="min-h-screen bg-[#fbf7ed] text-[#173d2d]"><DemoHeader /><main className="mx-auto max-w-6xl px-5 py-9"><Link href="/demo/jobs" className="inline-flex items-center gap-2 text-sm font-bold text-[#315c49]"><ArrowLeft className="size-4" /> Back to jobs</Link>
    <div className="mt-6 space-y-6">
      <DetailSection letter="A" title="Role at a glance"><div className="grid gap-6 md:grid-cols-[1fr_260px]"><div><p className="text-sm font-bold text-[#a1742d]">{job.company} · Synthetic demo role</p><h1 className="mt-2 font-serif text-5xl leading-tight">{job.title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-[#587064]">{job.summary}</p></div><dl className="metadata"><Meta label="Locations" value={job.locations.map((item) => `${item.label} (${item.workModes.join("/")})`).join(" · ")} /><Meta label="Travel" value={`${job.travelPercent}%`} /><Meta label="Requirements" value={`${job.requirements.filter((item) => item.scoringClass === "CORE").length} core · ${job.requirements.filter((item) => item.scoringClass === "PREFERRED").length} preferred`} /><Meta label="Analysis provider" value="Frozen synthetic contract" /><Meta label="Analyzed" value={new Date(job.analysisTimestamp).toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" }) + " UTC"} /></dl></div></DetailSection>

      <DetailSection letter="B" title="Overall decision"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><DecisionMetric label="Overall Fit Score" value={analysis.displayedScore === null ? "INSUFFICIENT EVIDENCE" : `${analysis.displayedScore} / 100`} /><DecisionMetric label="Score range" value={analysis.scoreRange ? `${analysis.scoreRange.low.toFixed(2)}–${analysis.scoreRange.high.toFixed(2)}` : "Not displayed"} /><DecisionMetric label="Evidence Quality" value={`${analysis.evidenceQuality.toFixed(1)} / 100`} /><DecisionMetric label="Apply Priority" value={analysis.applyPriority.replaceAll("_", " ")} /><DecisionMetric label="Confirmed blockers" value={String(analysis.confirmedBlockerCount)} /></div><div className="mt-5 flex flex-wrap gap-2"><span className="pill">{analysis.analysisStatus.replaceAll("_", " ")}</span><span className="pill">{candidate.label}</span></div><p className="mt-4 text-sm text-[#62796f]">{analysis.applyPriorityRule}</p>{analysis.ineligibilityReasons.map((reason) => <p key={reason} className="mt-3 rounded-xl bg-[#fff4d8] p-3 text-sm text-[#73551f]"><ShieldAlert className="mr-2 inline size-4" />{reason}</p>)}</DetailSection>

      <DetailSection letter="C" title="Score breakdown"><div className="grid gap-4 md:grid-cols-4"><ScorePart label="Core Fit" total={analysis.classTotals.core} /><ScorePart label="Preferred Coverage" total={analysis.classTotals.preferred} /><ScorePart label="Nice-to-Have" total={analysis.classTotals.niceToHave} /><div className="rounded-2xl bg-[#173d2d] p-5 text-[#fffaf0]"><p className="text-xs font-bold uppercase tracking-wide text-[#d7c58d]">Overall Fit</p><p className="mt-3 font-serif text-3xl">{analysis.numericScoreEligibility ? `${points(analysis.classTotals.totalEarnedMidMicroPoints)} / ${points(analysis.classTotals.totalMaximumMicroPoints)}` : "No numeric result"}</p></div></div><div className="mt-5 grid gap-3 rounded-xl bg-[#edf1e8] p-4 text-sm sm:grid-cols-3"><p>Unused preferred → Core: <b>{points(analysis.budgetTransfers.unusedPreferredToCoreMicroPoints)}</b></p><p>Unused nice → Core: <b>{points(analysis.budgetTransfers.unusedNiceToCoreMicroPoints)}</b></p><p>Exact visible maximum: <b>{points(analysis.classTotals.totalMaximumMicroPoints)}</b></p></div></DetailSection>

      <DetailSection letter="D" title="Why this score"><div className="grid gap-5 lg:grid-cols-3"><ContributionList title="Strongest positive contributors" rows={positive.map((group) => `${group.canonicalName}: +${points(group.earnedMidMicroPoints)} points`)} empty="No positive point contributors were eligible." /><ContributionList title="Largest point losses" rows={losses.map((group) => `${group.canonicalName}: −${points(group.pointsLostMicroPoints)} points`)} empty="No confirmed point losses." /><ContributionList title="Uncertainty contributors" rows={uncertain.map((group) => `${group.canonicalName}: ${group.matchClass.replaceAll("_", " ")}`)} empty="No material uncertainty contributors." /></div></DetailSection>

      <DetailSection letter="E" title="Requirement-by-requirement evidence"><div className="space-y-4">{analysis.capabilityGroups.map((group) => <article key={group.capabilityGroupId} className="rounded-2xl border border-[#173d2d]/10 bg-[#fffdf7] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-[#a1742d]">{group.scoringClass.replaceAll("_", " ")} · {group.importance} · {group.centrality.replaceAll("_", " ")}</p><h3 className="mt-1 font-serif text-xl">{group.canonicalName}</h3></div><span className="pill">{group.matchClass.replaceAll("_", " ")}</span></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><EvidenceQuote label="Job evidence" id={group.id} text={group.jobEvidence} /><EvidenceQuote label="Candidate evidence" id={group.candidateEvidenceIds.join(", ") || "No supported evidence ID"} text={group.candidateEvidenceIds.map((id) => evidence.get(id)?.text).filter(Boolean).join(" ") || (group.matchClass === "UNKNOWN" ? "The profile was searched, but the available information is insufficient to classify this requirement." : "The frozen synthetic profile contains no supporting evidence for this requirement.")} /></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-6"><Meta label="Maximum" value={points(group.maximumMicroPoints)} /><Meta label="Low" value={points(group.earnedLowMicroPoints)} /><Meta label="Mid" value={points(group.earnedMidMicroPoints)} /><Meta label="High" value={points(group.earnedHighMicroPoints)} /><Meta label="Points lost" value={points(group.pointsLostMicroPoints)} /><Meta label="Verifier" value={group.verifierStatus} /></dl><p className="mt-3 text-xs text-[#6b7e74]">Uncertainty: {group.uncertainty}</p></article>)}</div></DetailSection>

      <DetailSection letter="F" title="Experience analysis">{experienceRows.length ? <div className="space-y-4">{experienceRows.map((row) => <article key={row.requirementId} className="rounded-2xl border border-[#173d2d]/10 bg-[#fffdf7] p-5"><h3 className="font-serif text-xl">{analysis.capabilityGroups.find((group) => group.id === row.requirementId)?.canonicalName}</h3><dl className="mt-4 grid gap-3 sm:grid-cols-3"><Meta label="Requested" value={`${row.requestedYears} years · ${analysis.capabilityGroups.find((group) => group.id === row.requirementId)?.scoringClass}`} /><Meta label="Relevant-year range" value={`${row.relevantYears.toFixed(2)} years (frozen midpoint)`} /><Meta label="Maximum / earned" value={`${row.maximumPoints.toFixed(2)} / ${row.earnedPoints.toFixed(2)}`} /><Meta label="Intervals used" value={row.intervals.join(" · ")} /><Meta label="Relevance coefficients" value={row.coefficients.join(" · ")} /><Meta label="Overlapping months removed" value={String(row.overlappingMonthsRemoved)} /></dl></article>)}</div> : <p className="text-[#62796f]">This posting does not state a numeric experience requirement. No minimum years were fabricated.</p>}</DetailSection>

      <DetailSection letter="G" title="Matched evidence"><div className="grid gap-4 md:grid-cols-2">{positive.map((group) => <article key={group.id} className="rounded-2xl bg-[#edf4ea] p-5"><h3 className="font-bold">{group.canonicalName}</h3><p className="mt-2 text-sm leading-6"><b>Job:</b> {group.jobEvidence}</p><p className="mt-2 text-sm leading-6"><b>Candidate:</b> {group.candidateEvidenceIds.map((id) => evidence.get(id)?.text).filter(Boolean).join(" ")}</p><p className="mt-3 text-sm font-bold text-[#315c49]">{group.matchClass.replaceAll("_", " ")} · {points(group.earnedMidMicroPoints)} points earned</p></article>)}</div>{!positive.length && <p>No point-bearing matches are displayed because numeric-score eligibility failed.</p>}</DetailSection>

      <DetailSection letter="H" title="Missing or weak evidence"><div className="space-y-4">{analysis.capabilityGroups.filter((group) => ["NOT_EVIDENCED", "PARTIAL", "WEAK", "UNKNOWN"].includes(group.matchClass)).map((group) => <article key={group.id} className="rounded-2xl border border-[#b88d4a]/25 bg-[#fff8e8] p-5"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-bold">{group.canonicalName}</h3><span className="pill">{group.scoringClass} · {group.matchClass.replaceAll("_", " ")}</span></div><p className="mt-3 text-sm"><b>Job evidence:</b> {group.jobEvidence}</p><p className="mt-2 text-sm"><b>Searched profile evidence:</b> {group.candidateEvidenceIds.length ? group.candidateEvidenceIds.join(", ") : "No supporting evidence ID found"}</p><p className="mt-2 text-sm"><b>Points affected:</b> {points(group.pointsLostMicroPoints)}</p><p className="mt-2 text-sm"><b>Truthful preparation:</b> Prepare an existing, verifiable example or ask the employer to clarify the requirement. Do not invent experience.</p></article>)}</div>{!analysis.capabilityGroups.some((group) => ["NOT_EVIDENCED", "PARTIAL", "WEAK", "UNKNOWN"].includes(group.matchClass)) && <p className="text-sm text-[#62796f]">No missing or weak evidence is confirmed for this role.</p>}</DetailSection>

      <DetailSection letter="I" title="Practical constraints"><p className="mb-4 text-sm text-[#62796f]">These constraints affect visible priority or blocker status. They never change technical-fit points.</p><div className="grid gap-4 md:grid-cols-3">{analysis.practicalConstraints.map((constraint) => <article key={constraint.id} className={`rounded-2xl p-5 ${constraint.blocker ? "bg-[#f8e6df]" : "bg-[#edf4ea]"}`}><p className="text-xs font-bold uppercase tracking-wide">{constraint.id.replaceAll("_", " ")}</p><h3 className="mt-2 font-serif text-xl">{constraint.label}</h3><p className="mt-3 text-sm font-bold">{constraint.status.replaceAll("_", " ")} {constraint.blocker ? "· blocker" : ""}</p><p className="mt-2 text-sm leading-6 text-[#587064]">{constraint.explanation}</p></article>)}</div></DetailSection>

      <DetailSection letter="J" title="How the score works"><div className="grid gap-4 md:grid-cols-2"><InfoCard title="Class budgets" body="CORE begins at 85. Preferred is capped at 12 (including 4 for preferred experience). Nice-to-Have is capped at 3 and at 1 per independent group. Unused class capacity transfers visibly to CORE." /><InfoCard title="Capability allocation" body="Validated active CORE groups receive exact integer micro-points through stable largest-remainder allocation. One point equals 1,000,000 micro-points. Aliases and examples cannot create duplicate budgets." /><InfoCard title="Match intervals" body="Matched 1.00; Strong Equivalent 0.80/0.90/0.95; Partial 0.35/0.55/0.70; Weak 0.10/0.25/0.40; Not Evidenced and Explicit Conflict 0. Unknown stays unknown." /><InfoCard title="Evidence Quality" body="A versioned weighted geometric mean measures completeness and support. It is not confidence that the employer will hire the candidate." /></div><div className="mt-4 rounded-xl bg-[#173d2d] p-5 text-sm leading-7 text-[#fffaf0]"><p><b>Scorer:</b> jobpilot-ai-fit-v2.2</p><p><b>Formula:</b> earned = maximum micro-points × frozen match basis points ÷ 10,000; low, mid, and high reconcile independently.</p><p><b>No hidden adjustment:</b> 0</p><p>{SCORE_DISCLOSURE}</p><p>{CALIBRATION_DISCLOSURE}</p></div></DetailSection>

      <DetailSection letter="K" title="Score receipt"><div className="grid gap-5 lg:grid-cols-[1fr_320px]"><div className="overflow-auto rounded-2xl bg-[#132c22] p-5 text-xs leading-6 text-[#dce9df]"><pre>{JSON.stringify(analysis.receipt, null, 2)}</pre></div><div><p className="text-sm text-[#62796f]">Analysis ID</p><code className="mt-1 block break-all rounded-lg bg-white p-3 text-xs">{analysis.analysisId}</code><p className="mt-4 text-sm text-[#62796f]">Receipt hash</p><code className="mt-1 block break-all rounded-lg bg-white p-3 text-xs">{String(analysis.receipt.receiptHash)}</code><div className="mt-4 grid gap-2"><button type="button" onClick={downloadReceipt} className="button-primary justify-center"><Download className="size-4" /> Download JSON</button><button type="button" onClick={copyHash} className="button-secondary justify-center"><Clipboard className="size-4" /> {copied ? "Copied" : "Copy Receipt Hash"}</button></div><p className="mt-4 text-xs leading-5 text-[#687c72]">Content hashes, model metadata, scorer version, and exact reconciliation are included. The receipt contains no private resume data.</p></div></div></DetailSection>

      <section className="paper-card" aria-labelledby="strategy-title"><div className="flex flex-wrap items-center justify-between gap-5"><div><p className="eyebrow">Grounded next action</p><h2 id="strategy-title" className="mt-2 font-serif text-3xl">Build My Application Strategy</h2><p className="mt-2 text-sm text-[#62796f]">Candidate claims cite evidence IDs. Job claims cite requirement IDs. No application is submitted.</p></div><button type="button" disabled={strategyState === "RUNNING"} onClick={requestStrategy} className="button-primary"><Bot className="size-4" />{strategyState === "RUNNING" ? "Building…" : "Build My Application Strategy"}</button></div>{initialMode !== "BUILD_WEEK_GPT56" && <p className="mt-4 rounded-xl bg-[#fff4d8] p-3 text-sm font-semibold text-[#75561e]">Prepared demonstration output — live GPT-5.6 is not configured in this environment.</p>}{["MODEL_UNAVAILABLE", "FAILED"].includes(strategyState) && <p role="alert" className="mt-4 rounded-xl bg-[#f8e6df] p-3 text-sm font-semibold">AI analysis is temporarily unavailable. No result was generated.</p>}{strategyState === "RATE_LIMITED" && <p role="alert" className="mt-4 rounded-xl bg-[#fff4d8] p-3 text-sm font-semibold">The demo AI quota is reached for today. No result was generated.</p>}{strategy && <StrategyResult strategy={strategy} fixture={provider?.mode === "FIXTURE_ONLY"} />}</section>

      <div className="flex flex-wrap gap-3 pb-8"><button type="button" onClick={() => tracker.toggleSaved(job.id)} className="button-primary"><Bookmark className="size-4" fill={saved ? "currentColor" : "none"} />{saved ? "Unsave Job" : "Save Job"}</button>{saved && <Link href="/demo/tracker" className="button-secondary">View Tracker <ExternalLink className="size-4" /></Link>}</div>
    </div>
  </main></div>;
}

function DetailSection({ letter, title, children }: { letter: string; title: string; children: React.ReactNode }) { return <section className="paper-card"><div className="mb-5 flex items-center gap-3"><span className="grid size-8 place-items-center rounded-full bg-[#e7dcc1] font-mono text-xs font-bold text-[#8b6527]">{letter}</span><h2 className="font-serif text-3xl">{title}</h2></div>{children}</section>; }
function Meta({ label, value }: { label: string; value: string }) { return <div><dt className="text-[10px] font-bold uppercase tracking-[.13em] text-[#7b8d83]">{label}</dt><dd className="mt-1 text-sm font-semibold leading-5">{value}</dd></div>; }
function DecisionMetric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-[#edf1e8] p-4"><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#75877d]">{label}</p><p className="mt-2 font-serif text-xl leading-tight">{value}</p></div>; }
function ScorePart({ label, total }: { label: string; total: { maximumMicroPoints: number; earnedMidMicroPoints: number } }) { return <div className="rounded-2xl bg-[#edf1e8] p-5"><p className="text-xs font-bold uppercase tracking-wide text-[#75877d]">{label}</p><p className="mt-3 font-serif text-3xl">{points(total.earnedMidMicroPoints)} <span className="text-base text-[#6b7d73]">/ {points(total.maximumMicroPoints)}</span></p></div>; }
function ContributionList({ title, rows, empty }: { title: string; rows: string[]; empty: string }) { return <article className="rounded-2xl bg-[#edf1e8] p-5"><h3 className="font-bold">{title}</h3><ul className="mt-3 space-y-2 text-sm leading-6 text-[#587064]">{(rows.length ? rows : [empty]).map((row) => <li key={row}>• {row}</li>)}</ul></article>; }
function EvidenceQuote({ label, id, text }: { label: string; id: string; text: string }) { return <div className="rounded-xl bg-[#edf1e8] p-4"><p className="text-xs font-bold uppercase tracking-wide text-[#75877d]">{label} · {id}</p><p className="mt-2 text-sm leading-6 text-[#4f685c]">{text}</p></div>; }
function InfoCard({ title, body }: { title: string; body: string }) { return <article className="rounded-2xl bg-[#edf1e8] p-5"><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#587064]">{body}</p></article>; }
function StrategyResult({ strategy, fixture }: { strategy: ApplicationStrategy; fixture: boolean }) { return <div className="mt-5"><p className="text-xs font-bold uppercase tracking-[.13em] text-[#a1742d]">{fixture ? "FIXTURE_ONLY · prepared demonstration output" : "Live GPT-5.6 · structured output"}</p><div className="mt-3 rounded-2xl bg-[#edf4ea] p-5"><h3 className="font-serif text-2xl">{strategy.recommendation} — {strategy.rationale}</h3></div><div className="mt-4 grid gap-4 md:grid-cols-2"><StrategyCard title="Strongest evidence" rows={strategy.strongestFitEvidence.map((item) => `${item.requirementId} ← ${item.evidenceId}: ${item.explanation}`)} /><StrategyCard title="Largest truthful gaps" rows={strategy.truthfulGaps.map((item) => `${item.requirementId}: ${item.explanation}`)} /><StrategyCard title="Resume emphasis" rows={strategy.resumeEmphasis.map((item) => `${item.evidenceId}: ${item.recommendation}`)} /><StrategyCard title="Interview preparation" rows={strategy.interviewTopics.map((item) => `${item.requirementId}: ${item.topic}`)} /><StrategyCard title="Research before applying" rows={strategy.researchQuestions.map((item) => `${item.requirementId}: ${item.question}`)} /><StrategyCard title="Constraints to clarify" rows={strategy.practicalConstraintsToClarify.map((item) => `${item.constraintId}: ${item.question}`)} /><StrategyCard title="Limitations" rows={strategy.limitations} /></div></div>; }
function StrategyCard({ title, rows }: { title: string; rows: string[] }) { return <article className="rounded-2xl border border-[#173d2d]/10 bg-[#fffdf7] p-5"><h3 className="font-bold">{title}</h3><ul className="mt-3 space-y-2 text-sm leading-6 text-[#587064]">{rows.length ? rows.map((row) => <li key={row}>• {row}</li>) : <li>• Nothing additional is supported by the frozen evidence.</li>}</ul></article>; }
