import { Bot, CheckCircle2, FileCheck2, Fingerprint, Lightbulb, ShieldAlert } from "lucide-react";
import { PREPARED_ANALYSIS_CHALLENGE, PREPARED_APPLICATION_STRATEGY, PREPARED_REVIEW_BADGE, PREPARED_REVIEW_DISCLOSURE, PREPARED_REVIEW_PROOF, PREPARED_REVIEW_PROVENANCE } from "@/lib/prepared-reviews";

export function PreparedReviewProof() {
  const strategy = PREPARED_APPLICATION_STRATEGY.output;
  const challenge = PREPARED_ANALYSIS_CHALLENGE.output.questionableMatches[0];
  return <div>
    <div className="flex flex-wrap items-start justify-between gap-5"><div><p className="eyebrow"><Fingerprint className="size-4" /> Frozen, bounded, inspectable</p><h2 className="mt-3 font-serif text-3xl">{PREPARED_REVIEW_BADGE}</h2><p className="mt-3 max-w-3xl text-[#587064]">{PREPARED_REVIEW_DISCLOSURE}</p></div><div className="flex flex-wrap gap-2 text-xs"><span className="pill"><CheckCircle2 className="size-3" /> Provenance verified</span><span className="pill">API requests: 0</span><span className="pill">Final score: No</span></div></div>
    <dl className="mt-6 grid gap-3 rounded-2xl bg-[#edf1e8] p-5 text-sm sm:grid-cols-2 lg:grid-cols-4"><ProofFact label="Generation surface" value={PREPARED_REVIEW_PROVENANCE.generationSurface} /><ProofFact label="Model family" value={PREPARED_REVIEW_PROVENANCE.modelFamily} /><ProofFact label="OpenAI API cost" value="$0" /><ProofFact label="Runtime mode" value="Prepared, not live" /></dl>
    <section aria-labelledby="prepared-artifacts-title" className="mt-7"><h3 id="prepared-artifacts-title" className="font-serif text-2xl">Four hash-bound review artifacts</h3><div className="mt-4 grid gap-4 lg:grid-cols-2">{PREPARED_REVIEW_PROOF.map((artifact) => <article key={artifact.type} className="min-w-0 rounded-2xl border border-[#173d2d]/10 bg-[#fffdf7] p-5"><div className="flex items-start justify-between gap-3"><div><p className="metric-label">{artifact.type.replaceAll("_", " ")}</p><h4 className="mt-2 font-serif text-xl">{artifact.label}</h4></div><FileCheck2 className="size-5 shrink-0 text-[#a1742d]" /></div><dl className="mt-5 space-y-3 text-xs"><HashFact label="Frozen input" value={artifact.frozenInputHash} /><HashFact label="Output" value={artifact.outputHash} /><HashFact label="File" value={artifact.fileSha256} /></dl><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><ProofFact label="Valid evidence IDs" value={String(artifact.validEvidenceIds.length)} /><ProofFact label="Invalid IDs" value={String(artifact.invalidEvidenceIds)} /><ProofFact label="API requests" value={String(artifact.apiRequestCount)} /><ProofFact label="Model final score" value={artifact.modelGeneratedFinalScore ? "Yes" : "No"} /></div><details className="mt-4 rounded-xl bg-[#edf1e8] p-3 text-xs"><summary className="cursor-pointer font-bold">Inspect valid evidence IDs</summary><p className="mt-2 break-words font-mono leading-5 text-[#587064]">{artifact.validEvidenceIds.join(" · ")}</p></details></article>)}</div></section>
    <section className="mt-7 grid gap-4 lg:grid-cols-2"><article className="rounded-2xl border border-[#315c49]/15 bg-[#e8efe6] p-5"><Lightbulb className="size-5 text-[#a1742d]" /><p className="metric-label mt-4">Concrete strategy example</p><h3 className="mt-2 font-serif text-2xl">Lead with tested integration safeguards</h3><p className="mt-3 text-sm leading-7 text-[#486458]">{strategy.resumeEmphasis[0]?.recommendation}</p><p className="mt-4 text-xs font-bold">Evidence ID: {strategy.resumeEmphasis[0]?.evidenceId} · Recommendation: {strategy.recommendation}</p></article><article className="rounded-2xl border border-[#a1742d]/20 bg-[#fff4d8] p-5"><ShieldAlert className="size-5 text-[#8b5f21]" /><p className="metric-label mt-4">Concrete challenge example</p><h3 className="mt-2 font-serif text-2xl">Keep semantic equivalence reviewable</h3><p className="mt-3 text-sm leading-7 text-[#695d44]">{challenge?.assessment}</p><p className="mt-4 text-xs font-bold">Requirement: {challenge?.requirementId} · Evidence: {challenge?.evidenceIds.join(", ")}</p></article></section>
    <div className="mt-6 flex items-start gap-3 rounded-xl bg-[#173d2d] p-4 text-sm leading-6 text-[#fffaf0]"><Bot className="mt-0.5 size-5 shrink-0 text-[#d7c68d]" /><p><b>No hidden reasoning is published.</b> Only final structured outputs, bounded evidence IDs, hashes, limitations, and provenance are stored. Prepared review may recommend deterministic reanalysis; it cannot silently change Fit Score or a receipt.</p></div>
  </div>;
}

function ProofFact({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-xl bg-white/55 p-3"><dt className="metric-label">{label}</dt><dd className="mt-1 break-words font-bold">{value}</dd></div>; }
function HashFact({ label, value }: { label: string; value: string }) { return <div className="grid min-w-0 gap-1 sm:grid-cols-[90px_1fr]"><dt className="font-bold text-[#6d8176]">{label}</dt><dd className="min-w-0 break-all font-mono leading-5">{value}</dd></div>; }
