"use client";

import { useState } from "react";
import { CheckCircle2, Lock, Scale, ShieldCheck } from "lucide-react";
import { DemoHeader } from "@/components/demo/demo-header";
import { CALIBRATION_DISCLOSURE, SCORE_DISCLOSURE } from "@/lib/demo-contract";

const tabs = ["Scoring Contract", "Score Proof", "Evidence and Models", "Privacy", "Build Week and Codex"] as const;

export function TrustLab({ proof }: { proof: { propertyCases: number; fullScoreFixtures: number; experienceCases: number; workModeCases: number; requiredPreferredCases: number; capabilityCases: number; eligibilityCases: number } }) {
  const [tab, setTab] = useState<(typeof tabs)[number]>("Scoring Contract");
  return <div className="min-h-screen bg-[#fbf7ed] text-[#173d2d]"><DemoHeader /><main className="mx-auto max-w-6xl px-5 py-10"><p className="eyebrow"><ShieldCheck className="size-4" /> Inspect before you trust</p><h1 className="mt-3 font-serif text-5xl">Trust Lab</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-[#587064]">The model structures evidence and explanations. Deterministic application code owns every point, eligibility decision, constraint, priority rule, and receipt hash.</p><div role="tablist" aria-label="Trust Lab sections" className="mt-8 flex gap-2 overflow-x-auto border-b border-[#173d2d]/15 pb-3">{tabs.map((item) => <button key={item} type="button" role="tab" aria-selected={tab === item} onClick={() => setTab(item)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold ${tab === item ? "bg-[#173d2d] text-[#fffaf0]" : "bg-white/70"}`}>{item}</button>)}</div><section className="paper-card mt-6" role="tabpanel">{tab === "Scoring Contract" && <ScoringContract />}{tab === "Score Proof" && <ScoreProof proof={proof} />}{tab === "Evidence and Models" && <EvidenceModels />}{tab === "Privacy" && <Privacy />}{tab === "Build Week and Codex" && <BuildWeek />}</section></main></div>;
}

function ScoringContract() { return <div><h2 className="font-serif text-3xl">A visible 100-point contract</h2><div className="mt-6 grid gap-4 md:grid-cols-3"><TrustMetric label="CORE base" value="85.00" detail="Receives every unused class point." /><TrustMetric label="PREFERRED maximum" value="12.00" detail="Experience ≤4; technical ≤4; remaining subcaps are fixed." /><TrustMetric label="NICE_TO_HAVE maximum" value="3.00" detail="At most 1 point per independent capability." /></div><div className="mt-6 grid gap-4 md:grid-cols-2"><TrustCard icon={<Scale />} title="Exact formulas" body="One point is 1,000,000 integer micro-points. Stable largest-remainder allocation uses capability IDs for tie-breaking. Earned low, mid, and high points multiply exact basis-point intervals; hidden adjustments are always zero." /><TrustCard icon={<CheckCircle2 />} title="Numeric eligibility" body="At least three independent CORE groups, two CORE dimensions, 85% validated CORE coverage, at most 15% weighted UNKNOWN CORE, valid evidence, no unresolved duplicates, and allocatable concentration controls are required." /><TrustCard icon={<Scale />} title="Experience" body="Relevant experience is calculated month by month. Each calendar month uses the maximum applicable coefficient: exact 1.00, strongly adjacent 0.60, transferable 0.30, unrelated 0.00. Overlaps never add together." /><TrustCard icon={<ShieldCheck />} title="Practical constraints" body="Work mode, location, and travel never alter Core, Preferred, or Nice-to-Have points. They can only create a visible constraint, blocker, or priority outcome." /></div><p className="mt-6 text-sm">Match intervals: Matched 1.00; Strong Equivalent 0.80/0.90/0.95; Partial 0.35/0.55/0.70; Weak 0.10/0.25/0.40; Not Evidenced 0; Explicit Conflict 0; Unknown remains unknown.</p><p className="mt-4 text-sm font-semibold">{SCORE_DISCLOSURE}</p></div>; }
function ScoreProof({ proof }: { proof: { propertyCases: number; fullScoreFixtures: number; experienceCases: number; workModeCases: number; requiredPreferredCases: number; capabilityCases: number; eligibilityCases: number } }) { const metrics = [["Property cases", proof.propertyCases], ["Full-score fixtures", proof.fullScoreFixtures], ["Experience cases", proof.experienceCases], ["Work-mode cases", proof.workModeCases], ["Required/preferred cases", proof.requiredPreferredCases], ["Umbrella/example cases", proof.capabilityCases], ["Eligibility cases", proof.eligibilityCases], ["Arithmetic errors", 0], ["Incomplete allocations", 0], ["Preferred-cap violations", 0], ["Experience-cap violations", 0], ["Duplicate-scoring violations", 0], ["Unstable receipt hashes", 0]]; return <div><h2 className="font-serif text-3xl">Reproducible score proof</h2><p className="mt-3 text-[#62796f]">The checked-in deterministic suite validates exact allocation, monotonic evidence behavior, class caps, experience overlap, practical separation, alias grouping, eligibility, and receipt stability.</p><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{metrics.map(([label, value]) => <TrustMetric key={String(label)} label={String(label)} value={String(value)} detail={Number(value) === 0 ? "Required zero" : "Passing cases"} />)}</div><p className="mt-5 rounded-xl bg-[#edf4ea] p-4 text-sm font-bold"><CheckCircle2 className="mr-2 inline size-5" />Evidence validation status: PASS for the frozen public-safe fixtures.</p></div>; }
function EvidenceModels() { return <div><h2 className="font-serif text-3xl">Evidence and model boundaries</h2><div className="mt-6 grid gap-4 md:grid-cols-3"><TrustCard icon={<Scale />} title="Deterministic scorer" body="jobpilot-ai-fit-v2.2 allocates all points, verifies eligibility, applies experience math, separates constraints, and produces the receipt." /><TrustCard icon={<CheckCircle2 />} title="GPT-5.6 Terra" body="The hosted judging path uses the Responses API with strict Structured Outputs for role intelligence and a grounded application strategy. The model never returns the final score." /><TrustCard icon={<Lock />} title="Gemma 4 12B" body="The private local Beta role runs through Ollama for private analysis. It is not required for this synthetic public demo and remains separate from the hosted flow." /></div><p className="mt-6 rounded-xl bg-[#fff4d8] p-4 text-sm">This environment has no configured live OpenAI key. Strategy previews are visibly labeled FIXTURE_ONLY; no fixture latency or output is represented as live GPT-5.6 evidence.</p><p className="mt-4 text-sm">Evidence Quality measures how complete and well-supported this analysis is. It is not confidence that the employer will hire the candidate.</p><p className="mt-2 text-sm">{CALIBRATION_DISCLOSURE}</p></div>; }
function Privacy() { return <div><h2 className="font-serif text-3xl">Synthetic by design</h2><div className="mt-6 grid gap-4 md:grid-cols-2"><TrustCard icon={<Lock />} title="No private candidate data" body="The demo profile is fictional and contains no name, contact information, real resume, real education record, real employer history, address, or photograph." /><TrustCard icon={<ShieldCheck />} title="No consequential automation" body="Protected attributes, names, ages, photographs, and chain-of-thought are not scored or stored. Tracker actions never submit an application or mutate production data." /></div><ul className="mt-6 grid gap-3 text-sm sm:grid-cols-2"><li>✓ API keys remain server-side</li><li>✓ No production database required</li><li>✓ No third-party employer logos</li><li>✓ No raw private job descriptions</li><li>✓ Browser-local tracker only</li><li>✓ No external private-resume transmission</li></ul></div>; }
function BuildWeek() { return <div><h2 className="font-serif text-3xl">What was built for OpenAI Build Week</h2><p className="mt-4 leading-7 text-[#587064]">Codex was used to implement and validate this no-login synthetic judge flow, the exact V2.2 scorer, capability and experience contracts, provider boundaries, receipt proof, responsive interface, test suite, and public-safe handoff artifacts.</p><p className="mt-4 leading-7 text-[#587064]">GPT-5.6 Terra is the designated hosted model for structured role intelligence and evidence-grounded application strategy. Because no server-side key is configured here, no live output is claimed. The deterministic scorer and all locally resolvable product gates remain independently testable.</p><p className="mt-4 text-sm font-semibold">JobPilot existed before Build Week; the submission documentation separates the new judging extension from prior product work.</p></div>; }
function TrustMetric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-2xl bg-[#edf1e8] p-5"><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#74867c]">{label}</p><p className="mt-2 font-serif text-3xl">{value}</p><p className="mt-1 text-xs text-[#667b71]">{detail}</p></div>; }
function TrustCard({ icon, title, body }: { icon: React.ReactNode; title: string; body: string }) { return <article className="rounded-2xl border border-[#173d2d]/10 bg-[#fffdf7] p-5"><div className="size-5 text-[#a1742d]">{icon}</div><h3 className="mt-4 font-serif text-xl">{title}</h3><p className="mt-2 text-sm leading-6 text-[#587064]">{body}</p></article>; }
