"use client";

import { useState } from "react";
import { Bot, CheckCircle2, Cpu, Lock, Scale, ShieldCheck } from "lucide-react";
import { DemoHeader } from "@/components/demo/demo-header";
import { CALIBRATION_DISCLOSURE, SCORE_DISCLOSURE } from "@/lib/demo-contract";

const tabs = ["How AI is divided", "Why Gemma is primary", "When GPT-5.6 is used", "How the score is proved", "Current limitations"] as const;
type Proof = { propertyCases: number; fullScoreFixtures: number; experienceCases: number; workModeCases: number; requiredPreferredCases: number; capabilityCases: number; eligibilityCases: number };

export function TrustLab({ proof }: { proof: Proof }) {
  const [tab, setTab] = useState<(typeof tabs)[number]>(tabs[0]);
  return <div className="min-h-screen bg-[#fbf7ed] text-[#173d2d]"><DemoHeader /><main className="mx-auto max-w-6xl px-5 py-10"><p className="eyebrow"><ShieldCheck className="size-4" /> Inspect before you trust</p><h1 className="mt-3 font-serif text-5xl">Trust Lab</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-[#587064]">JobPilot is local-first and hybrid by design: Gemma handles primary semantic analysis, deterministic code owns every score, and GPT-5.6 is optional for explicit heavy reasoning.</p><div data-testid="trust-tabs" role="tablist" aria-label="Trust Lab sections" className="mt-8 flex gap-2 overflow-x-auto border-b border-[#173d2d]/15 pb-3">{tabs.map((item, index) => <button key={item} id={`trust-tab-${index}`} type="button" role="tab" aria-selected={tab === item} aria-controls="trust-panel" onClick={() => setTab(item)} className={`min-h-11 whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold ${tab === item ? "bg-[#173d2d] text-[#fffaf0]" : "bg-white/70"}`}>{item}</button>)}</div><section id="trust-panel" aria-labelledby={`trust-tab-${tabs.indexOf(tab)}`} className="paper-card mt-6" role="tabpanel">{tab === "How AI is divided" && <Division />}{tab === "Why Gemma is primary" && <Gemma />}{tab === "When GPT-5.6 is used" && <OpenAi />}{tab === "How the score is proved" && <ScoreProof proof={proof} />}{tab === "Current limitations" && <Limitations />}</section></main></div>;
}

function Division() { return <div><h2 className="font-serif text-3xl">Four explicit responsibility lanes</h2><div data-testid="responsibility-diagram" className="mt-6 grid overflow-hidden rounded-2xl border border-[#173d2d]/10 bg-[#edf1e8] md:grid-cols-3"><ResponsibilityLane label="Primary semantic analysis" value="Local Gemma 4 12B" tone="bg-[#dce9df]" /><ResponsibilityLane label="Exact scoring & receipt" value="Deterministic code" tone="bg-[#e9e2cf]" /><ResponsibilityLane label="User-invoked strategy" value="Optional GPT-5.6" tone="bg-[#e6e5db]" /></div><div className="mt-6 grid gap-4 md:grid-cols-2"><TrustCard icon={<Scale />} title="Deterministic Code" body="Cleans explicit text, parses work mode and years, unions experience months, normalizes aliases, allocates every point, measures Evidence Quality, separates constraints, sets priority, caches identities, and creates the Score Receipt." /><TrustCard icon={<Cpu />} title="Gemma 4 12B" body="Primary semantic model for ambiguous requirement extraction, capability grouping, importance, centrality, semantic candidate profiling, batched evidence matching, equivalence, role summary, and uncertainty." /><TrustCard icon={<Bot />} title="GPT-5.6 Terra" body="Optional heavy model for application strategy, independent critique, difficult ambiguity, and comparing two strategies. It never performs routine parsing or numeric scoring." /><TrustCard icon={<Lock />} title="Fixture Mode" body="Used only for deterministic tests, browser QA, video contingency, and no-key demonstration output. It is always labeled as prepared and never represented as fresh inference." /></div></div>; }
function ResponsibilityLane({ label, value, tone }: { label: string; value: string; tone: string }) { return <div className={`p-5 md:border-r md:border-[#173d2d]/10 md:last:border-0 ${tone}`}><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#708178]">{label}</p><p className="mt-2 font-serif text-xl">{value}</p></div>; }
function Gemma() { return <div><h2 className="font-serif text-3xl">Why Gemma is primary</h2><div className="mt-6 grid gap-4 md:grid-cols-2"><TrustCard icon={<Lock />} title="Private by default" body="The architecture keeps actual private-user resume analysis on the user's local Ollama runtime. A cloud account is not required for primary semantic analysis." /><TrustCard icon={<Cpu />} title="On-device and offline-capable" body="Gemma can analyze ambiguous role text and evidence on the local machine. The public judge flow uses frozen synthetic prepared analyses so judges do not need Ollama." /></div><p className="mt-6 rounded-xl bg-[#edf4ea] p-4 text-sm font-semibold">Prepared with the local Gemma analysis pipeline from frozen synthetic inputs.</p></div>; }
function OpenAi() { return <div><h2 className="font-serif text-3xl">When GPT-5.6 is used</h2><div className="mt-6 grid gap-4 md:grid-cols-2"><TrustCard icon={<Bot />} title="Bounded heavy reasoning" body="Build My Application Strategy, Challenge This Analysis, Resolve Ambiguous Requirement, and Compare Two Application Strategies are explicit user-invoked actions." /><TrustCard icon={<ShieldCheck />} title="Never routine scoring" body="GPT-5.6 never parses every job card, receives a full raw resume in Build Week mode, generates the final score, adds hidden points, changes a receipt silently, or submits an application." /></div><p className="mt-6 rounded-xl bg-[#fff4d8] p-4 text-sm">When the server-side key and heavy feature flag are absent, prepared demonstration output remains available with no failed browser request and no fake live badge.</p></div>; }
function ScoreProof({ proof }: { proof: Proof }) { const metrics = [["Property cases", proof.propertyCases], ["Full-score fixtures", proof.fullScoreFixtures], ["Experience cases", proof.experienceCases], ["Work-mode cases", proof.workModeCases], ["Required/preferred cases", proof.requiredPreferredCases], ["Umbrella/example cases", proof.capabilityCases], ["Eligibility cases", proof.eligibilityCases], ["Arithmetic errors", 0], ["Hidden adjustments", 0], ["Duplicate-scoring errors", 0], ["Receipt instability", 0]]; return <div><h2 className="font-serif text-3xl">How the score is proved</h2><p className="mt-3 text-[#62796f]">Every eligible analysis allocates exactly 100 visible points. Required/preferred caps, month-level experience, practical separation, de-duplication, deterministic mutation, and receipt hashes are reproducibly tested.</p><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{metrics.map(([label, value]) => <TrustMetric key={String(label)} label={String(label)} value={String(value)} detail={Number(value) === 0 ? "Required zero" : "Passing cases"} />)}</div><p className="mt-5 rounded-xl bg-[#edf4ea] p-4 text-sm font-bold"><CheckCircle2 className="mr-2 inline size-5" />The model never generates the numeric score.</p><p className="mt-4 text-sm font-semibold">{SCORE_DISCLOSURE}</p></div>; }
function Limitations() { return <div><h2 className="font-serif text-3xl">Current limitations</h2><ul className="mt-6 space-y-4 text-sm leading-7 text-[#587064]"><li>• {CALIBRATION_DISCLOSURE}</li><li>• Optional GPT-5.6 heavy reasoning requires server-side configuration.</li><li>• The public demo uses only synthetic candidate and job data.</li><li>• Prepared Gemma analyses support reliable judging and are not presented as fresh inference.</li><li>• JobPilot does not predict employer decisions or submit applications.</li></ul><p className="mt-6 text-sm font-semibold">Codex helped implement, test, repair, audit, and package the Build Week extension; pre-existing JobPilot work remains separately disclosed.</p></div>; }
function TrustMetric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-2xl bg-[#edf1e8] p-5"><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#74867c]">{label}</p><p className="mt-2 font-serif text-3xl">{value}</p><p className="mt-1 text-xs text-[#667b71]">{detail}</p></div>; }
function TrustCard({ icon, title, body }: { icon: React.ReactNode; title: string; body: string }) { return <article className="rounded-2xl border border-[#173d2d]/10 bg-[#fffdf7] p-5"><div className="size-5 text-[#a1742d]">{icon}</div><h3 className="mt-4 font-serif text-xl">{title}</h3><p className="mt-2 text-sm leading-6 text-[#587064]">{body}</p></article>; }
