"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowRight, Bot, CheckCircle2, Clock3, Cpu, FileCheck2, Lock, MapPinned, Scale, ShieldCheck } from "lucide-react";
import { DemoHeader } from "@/components/demo/demo-header";
import { SCORE_DISCLOSURE } from "@/lib/demo-contract";
import { PREPARED_REVIEW_BADGE, PREPARED_REVIEW_DISCLOSURE } from "@/lib/prepared-reviews";

const tabs = ["How JobPilot Saves Time", "How Roles Are Prioritized", "How the Score Is Verified", "Why Gemma Is Primary", "What GPT-5.6 Contributed", "Privacy and Limitations"] as const;
type Proof = { propertyCases: number; fullScoreFixtures: number; experienceCases: number; workModeCases: number; requiredPreferredCases: number; capabilityCases: number; eligibilityCases: number };

export function TrustLab({ proof }: { proof: Proof }) {
  const [tab, setTab] = useState<(typeof tabs)[number]>(tabs[0]);
  function tabKey(event: React.KeyboardEvent<HTMLDivElement>) { const index = tabs.indexOf(tab); if (event.key === "ArrowRight" || event.key === "ArrowLeft") { event.preventDefault(); const direction = event.key === "ArrowRight" ? 1 : -1; const next = tabs[(index + direction + tabs.length) % tabs.length]!; setTab(next); document.getElementById(`trust-tab-${tabs.indexOf(next)}`)?.focus(); } }
  function downloadProof() { const url = URL.createObjectURL(new Blob([JSON.stringify({ scorerVersion: "jobpilot-ai-fit-v2.2", proof, arithmeticErrors: 0, hiddenAdjustments: 0, receiptInstability: 0, openAiApiRequests: 0, applicationSubmissions: 0 }, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = "jobpilot-proof-summary.json"; link.click(); URL.revokeObjectURL(url); }
  return <div className="min-h-screen bg-[#fbf7ed] text-[#173d2d]"><DemoHeader /><main className="mx-auto max-w-7xl px-5 py-10"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow"><ShieldCheck className="size-4" /> Faster decisions, safer action</p><h1 className="mt-3 font-serif text-5xl">Trust Lab</h1></div><div className="flex flex-wrap gap-3"><Link href="/demo/verify-receipt" className="button-primary">Verify a Score Receipt</Link><button type="button" onClick={downloadProof} className="button-secondary">Download Proof Summary</button></div></div><p className="mt-4 max-w-3xl text-lg leading-8 text-[#587064]">JobPilot reduces application fatigue while preserving user control: local resume analysis, deterministic priority, inspectable evidence, independently verifiable receipts, and a direct employer destination that never auto-applies.</p><DecisionChain /><div data-testid="trust-tabs" role="tablist" aria-label="Trust Lab sections" onKeyDown={tabKey} className="mt-8 grid grid-cols-1 gap-2 border-b border-[#173d2d]/15 pb-3 sm:grid-cols-2 xl:flex xl:overflow-x-auto">{tabs.map((item, index) => <button key={item} id={`trust-tab-${index}`} type="button" role="tab" aria-selected={tab === item} aria-controls="trust-panel" tabIndex={tab === item ? 0 : -1} onClick={() => setTab(item)} className={`min-h-11 w-full rounded-full px-4 py-2 text-sm font-bold xl:w-auto ${tab === item ? "bg-[#173d2d] text-[#fffaf0]" : "bg-white/70"}`}>{item}</button>)}</div><section id="trust-panel" aria-labelledby={`trust-tab-${tabs.indexOf(tab)}`} className="paper-card mt-6" role="tabpanel">{tab === "How JobPilot Saves Time" && <SavesTime />}{tab === "How Roles Are Prioritized" && <Prioritized />}{tab === "How the Score Is Verified" && <ScoreProof proof={proof} />}{tab === "Why Gemma Is Primary" && <Gemma />}{tab === "What GPT-5.6 Contributed" && <PreparedGpt />}{tab === "Privacy and Limitations" && <Limitations />}</section></main></div>;
}

function DecisionChain() { const chain = ["OFFICIAL-SOURCE DISCOVERY", "LOCAL RESUME ANALYSIS", "DETERMINISTIC PRIORITY", "INSPECTABLE EVIDENCE", "VERIFIABLE RECEIPT", "DIRECT EMPLOYER DESTINATION"]; return <ol aria-label="JobPilot decision chain" className="mt-8 grid overflow-hidden rounded-2xl border border-[#173d2d]/10 bg-[#edf1e8] sm:grid-cols-2 xl:grid-cols-6">{chain.map((item, index) => <li key={item} className="flex min-h-24 items-center gap-3 border-b border-[#173d2d]/10 p-4 text-xs font-bold leading-5 last:border-0 sm:border-r xl:border-b-0"><span className="text-[#a1742d]">{index + 1}</span>{item}{index < chain.length - 1 && <ArrowRight className="ml-auto hidden size-3 shrink-0 xl:block" />}</li>)}</ol>; }
function SavesTime() { return <div><h2 className="font-serif text-3xl">Move from scattered listings to a controlled next step</h2><div className="mt-6 grid gap-4 md:grid-cols-3"><TrustCard icon={<MapPinned />} title="One nearby view" body="Roles from the processed official-source portfolio appear in a profile-configured location view—without browser geolocation or a map API." /><TrustCard icon={<Clock3 />} title="Visible priority" body="Fit, Evidence Quality, blockers, location, and recency make the next review explicit instead of hiding it behind a feed." /><TrustCard icon={<FileCheck2 />} title="Direct destination" body="When a role deserves attention, JobPilot opens the employer destination. It never fills or submits the application." /></div></div>; }
function Prioritized() { return <div><h2 className="font-serif text-3xl">Technical fit and practical priority stay separate</h2><p className="mt-3 text-[#587064]">Best Match uses a deterministic order: numeric eligibility, blocker state, Fit Score, Evidence Quality, distance when applicable, posting date, and stable job ID. Nearest, Most Recent, and Highest Evidence Quality are separate visible sorts.</p><div className="mt-6 grid gap-4 md:grid-cols-2"><TrustCard icon={<Scale />} title="Technical Fit Score" body="Only validated capability evidence and the frozen 100-point contract contribute. Distance and work mode never change technical points." /><TrustCard icon={<MapPinned />} title="Practical compatibility" body="Configured location, radius, work mode, remote preference, travel, and blockers help decide whether to act without becoming hidden score adjustments." /></div></div>; }
function ScoreProof({ proof }: { proof: Proof }) { const metrics = [["Property cases", proof.propertyCases], ["Full-score fixtures", proof.fullScoreFixtures], ["Experience cases", proof.experienceCases], ["Work-mode cases", proof.workModeCases], ["Required/preferred cases", proof.requiredPreferredCases], ["Capability cases", proof.capabilityCases], ["Eligibility cases", proof.eligibilityCases], ["Arithmetic errors", 0], ["Hidden adjustments", 0], ["Receipt mismatches", 0]]; return <div><h2 className="font-serif text-3xl">Exact 100-point contract, independently verifiable</h2><p className="mt-3 text-[#587064]">The verifier reproduces canonical hashing, micro-point arithmetic, class caps, transfers, rounding, evidence IDs, and frozen source inputs. A receipt is never trusted merely because it is JSON.</p><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{metrics.map(([label, value]) => <TrustMetric key={String(label)} label={String(label)} value={String(value)} detail={Number(value) === 0 ? "Required zero" : "Passing cases"} />)}</div><div className="mt-6 flex flex-wrap items-center gap-4"><Link href="/demo/verify-receipt" className="button-primary">Verify a Score Receipt</Link><p className="text-sm font-bold"><CheckCircle2 className="mr-2 inline size-5" />The model never generates the numeric score.</p></div><p className="mt-4 text-sm font-semibold">{SCORE_DISCLOSURE}</p></div>; }
function Gemma() { return <div><h2 className="font-serif text-3xl">Why Gemma 4 12B is primary</h2><div className="mt-6 grid gap-4 md:grid-cols-2"><TrustCard icon={<Lock />} title="Private local analysis" body="Private-user resume analysis stays on the user’s loopback Ollama runtime. No cloud account or cloud resume transmission is required." /><TrustCard icon={<Cpu />} title="Primary semantic work" body="Gemma handles ambiguous role extraction, capability grouping, semantic candidate profiling, evidence matching, equivalence, role summary, and uncertainty." /></div><p className="mt-6 rounded-xl bg-[#edf4ea] p-4 text-sm font-semibold">The public judge flow uses prepared synthetic Gemma analyses; the local edition can run gemma4:12b live on loopback.</p></div>; }
function PreparedGpt() { return <div><h2 className="font-serif text-3xl">{PREPARED_REVIEW_BADGE}</h2><p className="mt-3 text-[#587064]">{PREPARED_REVIEW_DISCLOSURE}</p><div className="mt-6 grid gap-4 md:grid-cols-2"><TrustCard icon={<Bot />} title="Meaningful bounded review" body="Application strategy, challenge analysis, ambiguous-requirement review, and pairwise strategy comparison use frozen synthetic evidence and valid evidence IDs." /><TrustCard icon={<ShieldCheck />} title="Zero-API submitted runtime" body="OpenAI API requests: 0. API cost: $0. No live API response, no raw private resume, no model-generated score, and no application submission." /></div><p className="mt-6 rounded-xl bg-[#fff4d8] p-4 text-sm font-bold">Prepared review can recommend deterministic reanalysis, but it cannot silently change capability classes, Evidence Quality, Fit Score, or a Score Receipt.</p></div>; }
function Limitations() { return <div><h2 className="font-serif text-3xl">Privacy and limitations</h2><ul className="mt-6 space-y-4 text-sm leading-7 text-[#587064]"><li>• Production discovery architecture processes official and rights-eligible employer sources; public demonstration jobs are synthetic.</li><li>• Nearby results cover the processed portfolio—not every role in a market.</li><li>• Private resume analysis stays local; raw resume text is not logged or added to reports.</li><li>• The score is not a hiring or interview probability.</li><li>• Independent hiring-outcome calibration is not yet available.</li><li>• GPT-5.6 review is prepared through Codex, not live API inference.</li><li>• JobPilot opens employer destinations but never submits applications.</li></ul><p className="mt-6 text-sm font-semibold">Codex helped reproduce defects, prove scoring failures mathematically, repair the CSS pipeline, compress the decision UX, create regression tests, and package this reproducible RC.</p></div>; }
function TrustMetric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-2xl bg-[#edf1e8] p-5"><p className="text-[11px] font-bold uppercase tracking-[.13em] text-[#74867c]">{label}</p><p className="mt-2 font-serif text-3xl">{value}</p><p className="mt-1 text-xs text-[#667b71]">{detail}</p></div>; }
function TrustCard({ icon, title, body }: { icon: React.ReactNode; title: string; body: string }) { return <article className="rounded-2xl border border-[#173d2d]/10 bg-[#fffdf7] p-5"><div className="size-5 text-[#a1742d]">{icon}</div><h3 className="mt-4 font-serif text-xl">{title}</h3><p className="mt-2 text-sm leading-6 text-[#587064]">{body}</p></article>; }
